FROM alpine:3.14

RUN mkdir /u01

## otelcol-contrib_0.57.2_linux_amd64.tar.gz
COPY otelcol-contrib_0.57.2_linux_amd64.tar.gz /u01/otelcol-contrib_0.57.2_linux_amd64.tar.gz
COPY otel-loki-collector-config.yaml /u01/otel-loki-collector-config.yaml
RUN tar zxvf /u01/otelcol-contrib_0.57.2_linux_amd64.tar.gz -C /u01
ENV EXPORTERS_LOKI_ENDPOINT=localhost:3100/loki/api/v1/push
ENV EXPORTERS_LOKI_TENANT_ID=example

WORKDIR /u01
CMD ["./otelcol-contrib", "--config=./otel-loki-collector-config.yaml"]