FROM alpine:3.14

RUN mkdir /u01

## otelcol-contrib_0.57.2_linux_amd64.tar.gz
COPY otelcol-contrib_0.57.2_linux_amd64.tar.gz /u01/otelcol-contrib_0.57.2_linux_amd64.tar.gz
COPY otel-skywalking-collector-config.yaml /u01/otel-skywalking-collector-config.yaml
RUN tar zxvf /u01/otelcol-contrib_0.57.2_linux_amd64.tar.gz -C /u01
ENV EXPORTERS_JAEGER_ENDPOINT=localhost:14250

WORKDIR /u01
CMD ["./otelcol-contrib", "--config=./otel-skywalking-collector-config.yaml"]