FROM alpine:3.14

RUN mkdir /u01

## https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.70.0
COPY ../artifact/otelcol-contrib_0.70.0_linux_amd64.tar.gz /u01/otelcol-contrib_0.70.0_linux_amd64.tar.gz
RUN tar zxvf /u01/otelcol-contrib_0.70.0_linux_amd64.tar.gz -C /u01
ENV EXPORTERS_JAEGER_ENDPOINT=localhost:14250

WORKDIR /u01
## CMD ["sleep", "3600"]
CMD ["./otelcol-contrib", "--config=/u01/config/otel-collector-sampling-config.yaml"]